import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import DownloadCTA from '../components/DownloadCTA';

export default function MembersPage() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <main>
      <section className="page-header">
        <div className="container">
          <div className="section-badge"><span className="badge-dot"></span> For Members / Clients</div>
          <h1 className="page-title">Achieve Your Body Goals</h1>
          <p className="page-lead">
            Your complete health roadmap right in your pocket. Connect with your assigned herbal coach, follow custom meal roadmaps, and watch your metrics climb.
          </p>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '32px', marginBottom: '60px' }}>
            <div className="feature-grid-card">
              <div className="feature-grid-icon">📄</div>
              <h3>My Wellness Reports</h3>
              <p>Access every body metrics report generated by your coach in clean, interactive charts. Track your progress numbers over time.</p>
            </div>
            <div className="feature-grid-card">
              <div className="feature-grid-icon">🥗</div>
              <h3>Diet & Meal Compliance Logs</h3>
              <p>Review and check off meals, shakes, and supplement doses as you consume them to keep your coach updated in real-time.</p>
            </div>
            <div className="feature-grid-card">
              <div className="feature-grid-icon">🔔</div>
              <h3>Habit Trackers & Notifications</h3>
              <p>Get automated nudge alarms for critical wellness actions: hydration, supplements, and meal timings throughout the day.</p>
            </div>
          </div>

          <div style={{ background: 'var(--bg-light-green)', borderRadius: 'var(--radius-lg)', padding: '40px', border: '1px solid rgba(34, 197, 94, 0.2)' }}>
            <h2 style={{ fontSize: '1.8rem', marginBottom: '16px' }}>5-Step Member Getting Started Guide</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
              <p>1. Download Vizen from Google Play Store or App Store and select <strong>"I am a Member"</strong>.</p>
              <p>2. Enter your phone number and accept the <strong>invite code</strong> sent by your wellness coach.</p>
              <p>3. Access your personalized <strong>Body Composition Report</strong> to understand your baseline metrics.</p>
              <p>4. Follow your custom <strong>Meal & Herbal Diet Plan</strong>, marking off items as you eat.</p>
              <p>5. Enable push notifications for hydration and supplement <strong>nudge alarms</strong> to maintain your streak!</p>
            </div>
            <Link to="/download" className="btn btn-primary" style={{ marginTop: '24px' }}>Download Member App</Link>
          </div>
        </div>
      </section>

      <DownloadCTA />
    </main>
  );
}
